export const LOGIN_TEXTS = {
  loading: "טוען...",
  connected: "מחובר",
  loginTitle: "התחבר כדי להמשיך",
  continueWithGoogle: "המשך עם Google",
  continueWithApple: "המשך עם Apple",
  continueAsGuest: "המשך כאורח עם מספר טלפון",
  phoneLabel: "מספר טלפון",
  phonePlaceholder: "הכנס מספר טלפון",
  sendOtp: "שלח קוד אימות",
  sending: "שולח...",
  enterCode: "הכנס את הקוד בן 6 הספרות שנשלח ל",
  verifyCode: "אמת קוד",
  verifying: "מאמת...",
  backToPhone: "חזור למספר טלפון →",
  firstNameLabel: "שם פרטי",
  lastNameLabel: "שם משפחה",
  firstNamePlaceholder: "ישראל",
  lastNamePlaceholder: "ישראלי",
  completeDetails: "השלם את הפרטים",
  completed: "הושלם ✓",
} as const;

export const ERROR_MESSAGES = {
  phoneRequired: "אנא הכנס את מספר הטלפון שלך",
  phoneInvalid: "מספר הטלפון אינו תקין",
  otpSendFailed: "שליחת הקוד נכשלה",
  otpIncomplete: "אנא הכנס את הקוד המלא בן 6 הספרות",
  nameRequired: "אנא הכנס שם פרטי ושם משפחה",
  nameInfoNeeded: "אנא הוסף את שמך המלא להשלמת ההרשמה",
  otpInvalid: "קוד לא תקין",
  googleSignInFailed: "התחברות עם Google נכשלה",
  appleSignInFailed: "התחברות עם Apple נכשלה",
} as const;