import {
  Calculator,
  CreditCard,
  DollarSign,
  Globe,
  Percent,
  Tag,
  Target,
  TrendingUp,
  PlayCircle,
  Clock,
  Settings,
} from "lucide-react";
import { Block } from "../types";

export const availableBlocks: Block[] = [
  {
    id: "provider-selection",
    type: "provider-selection",
    name: "Provider Selection",
    description: "Select preferred and fallback eSIM providers",
    icon: <Settings className="h-4 w-4" />,
    color: "bg-slate-100 border-slate-300 text-slate-800",
  },
  {
    id: "base-price",
    type: "base-price", 
    name: "Base Price",
    description: "Initialize base price from bundle cost",
    icon: <PlayCircle className="h-4 w-4" />,
    color: "bg-gray-100 border-gray-300 text-gray-800",
  },
  {
    id: "discount",
    type: "discount",
    name: "Discount",
    description: "Apply percentage or fixed discount",
    icon: <Percent className="h-4 w-4" />,
    color: "bg-green-100 border-green-300 text-green-800",
    disabled: true, // TODO: Implement discount configuration
  },
  {
    id: "markup",
    type: "markup",
    name: "Markup",
    description: "Add markup to base price",
    icon: <TrendingUp className="h-4 w-4" />,
    color: "bg-blue-100 border-blue-300 text-blue-800",
  },
  {
    id: "fixed-price",
    type: "fixed-price",
    name: "Fixed Price",
    description: "Set a fixed price for the bundle",
    icon: <DollarSign className="h-4 w-4" />,
    color: "bg-purple-100 border-purple-300 text-purple-800",
  },
  {
    id: "processing-fee",
    type: "processing-fee",
    name: "Processing Fee",
    description: "Calculate payment processing fees",
    icon: <CreditCard className="h-4 w-4" />,
    color: "bg-orange-100 border-orange-300 text-orange-800",
  },
  {
    id: "keep-profit",
    type: "profit-constraint", // Maps to apply-profit-constraint in database
    name: "Keep Profit",
    description: "Maintain minimum profit margin",
    icon: <Target className="h-4 w-4" />,
    color: "bg-red-100 border-red-300 text-red-800",
  },
  {
    id: "psychological-rounding",
    type: "psychological-rounding",
    name: "Psychological Rounding",
    description: "Apply charm pricing (e.g., $9.99)",
    icon: <Calculator className="h-4 w-4" />,
    color: "bg-indigo-100 border-indigo-300 text-indigo-800",
  },
  {
    id: "region-rounding",
    type: "region-rounding",
    name: "Region Rounding",
    description: "Apply region-specific rounding rules",
    icon: <Globe className="h-4 w-4" />,
    color: "bg-teal-100 border-teal-300 text-teal-800",
  },
  {
    id: "coupon",
    type: "coupon",
    name: "Coupon",
    description: "Manage discount coupons and corporate domains",
    icon: <Tag className="h-4 w-4" />,
    color: "bg-amber-100 border-amber-300 text-amber-800",
    disabled: true, // TODO: Implement coupon configuration
  },
  {
    id: "unused-days-discount",
    type: "unused-days-discount",
    name: "Unused Days Discount",
    description: "Apply discount for unused days from previous bundle",
    icon: <Clock className="h-4 w-4" />,
    color: "bg-cyan-100 border-cyan-300 text-cyan-800",
  },
];