#!/bin/bash

# Simplified OAuth Setup for eSIM Go
# Works without Google Cloud Organization

PROJECT_ID="esim-go-465108"

echo "=================================="
echo "   OAuth Client Setup for eSIM Go"
echo "=================================="
echo ""
echo "Since we can't create an organization (billing permissions),"
echo "we'll use manual OAuth client creation."
echo ""
echo "📍 Go to: https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
echo ""
echo "Step 1: Configure OAuth Consent Screen"
echo "--------------------------------------"
echo "• User Type: External"
echo "• App name: Hiilo eSIM Go"
echo "• Support email: support@esim-go.com"
echo "• Authorized domains: esim-go.com"
echo ""
echo "Step 2: Create These OAuth Clients"
echo "-----------------------------------"
echo ""
echo "PRODUCTION (3 clients):"
echo "1. production-esim-go-web (Web application)"
echo "2. production-esim-go-admin (Web application)"
echo "3. production-esim-go-ios (iOS)"
echo ""
echo "DEVELOPMENT (3 clients):"
echo "1. dev-esim-go-web (Web application)"
echo "2. dev-esim-go-admin (Web application)"
echo "3. dev-esim-go-ios (iOS)"
echo ""
echo "Full configuration details are in: oauth-clients-config.tf"
echo ""
echo "Run 'terraform output oauth_setup_instructions' for detailed config"