-- ============================================================================
-- Pricing Strategy: Default Pricing Strategy
-- ============================================================================
-- Description: Standard pricing with markup, psychological rounding, and profit protection
-- Is Default: true
-- Version: 1
-- Created: 2025-08-03
-- ============================================================================

-- This file is now obsolete as we use pricing_blocks table directly
-- See individual pricing-rules files for actual block definitions