[build]
builder = "dockerfile"
dockerfilePath = "backend/server/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internalPort = 4000

# Environment variable requirements (set in Railway dashboard)
# NODE_ENV=production
# LOG_LEVEL=info
# PORT=4000
# REDIS_URL=${{Redis.REDIS_URL}}
# SUPABASE_URL=your-supabase-url
# SUPABASE_ANON_KEY=your-supabase-anon-key
# SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
# ESIM_GO_API_KEY=your-api-key
# JWT_SECRET=your-jwt-secret
# STRIPE_SECRET_KEY=your-stripe-secret-key
# STRIPE_PUBLISHABLE_KEY=your-stripe-publishable-key
# STRIPE_WEBHOOK_SECRET=your-stripe-webhook-secret