generatorName: typescript-fetch
inputSpec: https://ecng-transactions.azurewebsites.net/swagger/v1/swagger.json
outputDir: ./src/generated
additionalProperties:
  supportsES6: true
  npmName: "@hiilo/easycard"
  npmVersion: "1.0.0"
  withInterfaces: true
  withoutRuntimeChecks: true
  typescriptThreePlus: true
  modelPropertyNaming: camelCase
  enumPropertyNaming: UPPERCASE