generatorName: typescript-axios
inputSpec: ./airalo.openapi.json
outputDir: ./src/generated
skipValidateSpec: true
additionalProperties:
  npmName: "@airhalo/client"
  npmVersion: "1.0.0"
  supportsES6: true
  withInterfaces: true
  modelPropertyNaming: camelCase
  enumPropertyNaming: UPPERCASE
  stringEnums: true
  useSingleRequestParameter: true
  withSeparateModelsAndApi: true
  apiPackage: api
  modelPackage: models
  fileHeader: "/* tslint:disable */\n/* eslint-disable */\n// @ts-nocheck"
globalProperties:
  models: ""
  apis: ""
  supportingFiles: "ApiException.ts,base.ts,common.ts,configuration.ts,git_push.sh,index.ts"